import sys
from Bio.Seq import Seq

#An utility that takes a GFA generated by the maf_to_gfa script as input and
#glues it back into original genome(s)

def rev_comp(seq):
	rc = Seq(seq).reverse_complement()
	return str(rc)

if len(sys.argv) != 2:
	print "Usage: glue.py <GFA file>"
	exit()

segment = dict()

def spell_segment(sid):
	return segment[sid] if sid > 0 else rev_comp(segment[-sid])

def spell_path(path, k):
	spell = [spell_segment(s) for s in path]
	print ''.join(spell)

handle = open(sys.argv[1])
for line in handle:
	line = line.split()
	if len(line) > 0:
		if line[0] == 'S':
			sid, body = line[1], line[2]
			if sid not in segment:
				if body != '*':
					segment[int(sid)] = body
			else:
				print line
				sys.exit("Segment duplicate!")
		if line[0] == 'P':
			k = 0
			path = [int(x[-1] + x[:-1]) for x in line[2].split(',')]
			print '>' + line[1]
			spell_path(path, k)
handle.close()
